ARG base_image
ARG jaeger_version

FROM jaegertracing/jaeger-collector:$jaeger_version

FROM $base_image
COPY --from=0 /go/bin/collector-linux /go/bin/collector-linux
COPY jaeger-mongodb /bin/jaeger-mongodb

ENV SPAN_STORAGE_TYPE grpc-plugin
ENV GRPC_STORAGE_PLUGIN_BINARY /bin/jaeger-mongodb

ENTRYPOINT /go/bin/collector-linux
